all: pinyins.txt


pinyins.txt:
	awk -f genpinyins.awk -vlen=1 ../data/gb_char.table \
	../data/gbk_char.table > $@
	awk -f genpinyins.awk -vlen=2 ../data/gb_char.table >> $@


update-header:
	python3 genpinyinheader.py > ../src/storage/pinyin_parser_table.h


.PHONY: pinyins.txt
