all: pinyins.txt


pinyins.txt:
	awk -f genpinyins.awk -vlen=1 ../data/gb_char.table \
	../data/gbk_char.table > $@
	awk -f genpinyins.awk -vlen=2 ../data/gb_char.table >> $@


update-header:
	python3 genpinyinheader.py > ../src/storage/pinyin_parser_table.h
	python3 gendoublepinyinheader.py > ../src/storage/double_pinyin_table.h
	python3 genbopomofoheader.py > ../src/storage/chewing_table.h
	python3 genchewingkey.py > ../src/storage/chewing_enum.h


.PHONY: pinyins.txt
