static const PinyinKey __zhuyin_standard_map [][3] = 
{
/*   */{PinyinKey(1)     /* 1 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ! */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* " */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* # */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* $ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* % */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* & */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ' */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ( */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ) */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* * */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* + */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* , */{PinyinKey(42)   /* ea */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* - */{PinyinKey(66)   /* er */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* . */{PinyinKey(150)  /* ou */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* / */{PinyinKey(60)  /* eng */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 0 */{PinyinKey(18)   /* an */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 1 */{PinyinKey(240)   /* b */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 2 */{PinyinKey(960)   /* d */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 3 */{PinyinKey(3)     /* 3 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 4 */{PinyinKey(4)     /* 4 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 5 */{PinyinKey(5520) /* zh */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 6 */{PinyinKey(2)     /* 2 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 7 */{PinyinKey(5)     /* 5 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 8 */{PinyinKey(6)     /* a */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 9 */{PinyinKey(12)   /* ai */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* : */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ; */{PinyinKey(24)  /* ang */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* < */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* = */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* > */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ? */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* @ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* A */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* B */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* C */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* D */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* E */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* F */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* G */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* H */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* I */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* J */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* K */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* L */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* M */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* N */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* O */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* P */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Q */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* R */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* S */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* T */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* U */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* V */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* W */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* X */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Y */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Z */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* [ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* \ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ] */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ^ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* _ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ` */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* a */{PinyinKey(2400)  /* m */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* b */{PinyinKey(3120)  /* r */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* c */{PinyinKey(1440)  /* h */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* d */{PinyinKey(1920)  /* k */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* e */{PinyinKey(1680)  /* g */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* f */{PinyinKey(3600)  /* q */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* g */{PinyinKey(4080) /* sh */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* h */{PinyinKey(480)   /* c */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* i */{PinyinKey(138)   /* o */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* j */{PinyinKey(156)   /* u */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* k */{PinyinKey(36)    /* e */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* l */{PinyinKey(30)   /* ao */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* m */{PinyinKey(216)   /* v */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* n */{PinyinKey(3840)  /* s */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* o */{PinyinKey(48)   /* ei */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* p */{PinyinKey(54)   /* en */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* q */{PinyinKey(3360)  /* p */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* r */{PinyinKey(2160)  /* j */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* s */{PinyinKey(2640)  /* n */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* t */{PinyinKey(720)  /* ch */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* u */{PinyinKey(72)    /* i */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* v */{PinyinKey(4800)  /* x */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* w */{PinyinKey(4320)  /* t */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* x */{PinyinKey(2880)  /* l */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* y */{PinyinKey(5280)  /* z */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* z */{PinyinKey(1200)  /* f */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* { */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* | */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
};

static const PinyinKey __zhuyin_hsu_map [][3] = 
{
/*   */{PinyinKey(1)     /* 1 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ! */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* " */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* # */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* $ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* % */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* & */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ' */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ( */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ) */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* * */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* + */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* , */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* - */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* . */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* / */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 0 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 1 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 2 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 3 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 4 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 5 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 6 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 7 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 8 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 9 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* : */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ; */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* < */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* = */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* > */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ? */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* @ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* A */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* B */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* C */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* D */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* E */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* F */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* G */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* H */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* I */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* J */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* K */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* L */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* M */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* N */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* O */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* P */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Q */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* R */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* S */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* T */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* U */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* V */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* W */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* X */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Y */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Z */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* [ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* \ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ] */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ^ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* _ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ` */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* a */{PinyinKey(480)   /* c */, PinyinKey(48)   /* ei */, PinyinKey(0)      /*  */},
/* b */{PinyinKey(240)   /* b */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* c */{PinyinKey(4800)  /* x */, PinyinKey(4080) /* sh */, PinyinKey(0)      /*  */},
/* d */{PinyinKey(960)   /* d */, PinyinKey(2)     /* 2 */, PinyinKey(0)      /*  */},
/* e */{PinyinKey(72)    /* i */, PinyinKey(42)   /* ea */, PinyinKey(0)      /*  */},
/* f */{PinyinKey(1200)  /* f */, PinyinKey(3)     /* 3 */, PinyinKey(0)      /*  */},
/* g */{PinyinKey(1680)  /* g */, PinyinKey(36)    /* e */, PinyinKey(0)      /*  */},
/* h */{PinyinKey(1440)  /* h */, PinyinKey(138)   /* o */, PinyinKey(0)      /*  */},
/* i */{PinyinKey(12)   /* ai */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* j */{PinyinKey(2160)  /* j */, PinyinKey(5520) /* zh */, PinyinKey(4)     /* 4 */},
/* k */{PinyinKey(1920)  /* k */, PinyinKey(24)  /* ang */, PinyinKey(0)      /*  */},
/* l */{PinyinKey(2880)  /* l */, PinyinKey(60)  /* eng */, PinyinKey(66)   /* er */},
/* m */{PinyinKey(2400)  /* m */, PinyinKey(18)   /* an */, PinyinKey(0)      /*  */},
/* n */{PinyinKey(2640)  /* n */, PinyinKey(54)   /* en */, PinyinKey(0)      /*  */},
/* o */{PinyinKey(150)  /* ou */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* p */{PinyinKey(3360)  /* p */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* q */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* r */{PinyinKey(3120)  /* r */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* s */{PinyinKey(3840)  /* s */, PinyinKey(5)     /* 5 */, PinyinKey(0)      /*  */},
/* t */{PinyinKey(4320)  /* t */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* u */{PinyinKey(216)   /* v */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* v */{PinyinKey(3600)  /* q */, PinyinKey(720)  /* ch */, PinyinKey(0)      /*  */},
/* w */{PinyinKey(30)   /* ao */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* x */{PinyinKey(156)   /* u */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* y */{PinyinKey(6)     /* a */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* z */{PinyinKey(5280)  /* z */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* { */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* | */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
};

static const PinyinKey __zhuyin_ibm_map [][3] = 
{
/*   */{PinyinKey(1)     /* 1 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ! */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* " */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* # */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* $ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* % */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* & */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ' */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ( */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ) */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* * */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* + */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* , */{PinyinKey(3)     /* 3 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* - */{PinyinKey(1440)  /* h */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* . */{PinyinKey(4)     /* 4 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* / */{PinyinKey(5)     /* 5 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 0 */{PinyinKey(1920)  /* k */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 1 */{PinyinKey(240)   /* b */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 2 */{PinyinKey(3360)  /* p */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 3 */{PinyinKey(2400)  /* m */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 4 */{PinyinKey(1200)  /* f */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 5 */{PinyinKey(960)   /* d */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 6 */{PinyinKey(4320)  /* t */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 7 */{PinyinKey(2640)  /* n */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 8 */{PinyinKey(2880)  /* l */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 9 */{PinyinKey(1680)  /* g */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* : */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ; */{PinyinKey(30)   /* ao */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* < */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* = */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* > */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ? */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* @ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* A */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* B */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* C */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* D */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* E */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* F */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* G */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* H */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* I */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* J */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* K */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* L */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* M */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* N */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* O */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* P */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Q */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* R */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* S */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* T */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* U */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* V */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* W */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* X */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Y */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Z */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* [ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* \ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ] */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ^ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* _ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ` */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* a */{PinyinKey(72)    /* i */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* b */{PinyinKey(60)  /* eng */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* c */{PinyinKey(54)   /* en */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* d */{PinyinKey(216)   /* v */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* e */{PinyinKey(4800)  /* x */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* f */{PinyinKey(6)     /* a */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* g */{PinyinKey(138)   /* o */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* h */{PinyinKey(36)    /* e */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* i */{PinyinKey(5280)  /* z */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* j */{PinyinKey(42)   /* ea */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* k */{PinyinKey(12)   /* ai */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* l */{PinyinKey(48)   /* ei */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* m */{PinyinKey(2)     /* 2 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* n */{PinyinKey(66)   /* er */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* o */{PinyinKey(480)   /* c */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* p */{PinyinKey(3840)  /* s */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* q */{PinyinKey(2160)  /* j */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* r */{PinyinKey(5520) /* zh */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* s */{PinyinKey(156)   /* u */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* t */{PinyinKey(720)  /* ch */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* u */{PinyinKey(3120)  /* r */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* v */{PinyinKey(24)  /* ang */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* w */{PinyinKey(3600)  /* q */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* x */{PinyinKey(18)   /* an */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* y */{PinyinKey(4080) /* sh */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* z */{PinyinKey(150)  /* ou */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* { */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* | */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
};

static const PinyinKey __zhuyin_gin_yieh_map [][3] = 
{
/*   */{PinyinKey(1)     /* 1 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ! */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* " */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* # */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* $ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* % */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* & */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ' */{PinyinKey(60)  /* eng */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ( */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ) */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* * */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* + */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* , */{PinyinKey(6)     /* a */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* - */{PinyinKey(54)   /* en */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* . */{PinyinKey(12)   /* ai */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* / */{PinyinKey(18)   /* an */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 0 */{PinyinKey(48)   /* ei */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 1 */{PinyinKey(5)     /* 5 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 2 */{PinyinKey(240)   /* b */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 3 */{PinyinKey(960)   /* d */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 4 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 5 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 6 */{PinyinKey(5520) /* zh */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 7 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 8 */{PinyinKey(72)    /* i */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 9 */{PinyinKey(138)   /* o */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* : */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ; */{PinyinKey(150)  /* ou */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* < */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* = */{PinyinKey(66)   /* er */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* > */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ? */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* @ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* A */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* B */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* C */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* D */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* E */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* F */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* G */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* H */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* I */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* J */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* K */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* L */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* M */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* N */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* O */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* P */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Q */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* R */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* S */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* T */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* U */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* V */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* W */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* X */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Y */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Z */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* [ */{PinyinKey(24)  /* ang */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* \ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ] */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ^ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* _ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ` */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* a */{PinyinKey(3)     /* 3 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* b */{PinyinKey(4800)  /* x */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* c */{PinyinKey(2880)  /* l */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* d */{PinyinKey(2640)  /* n */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* e */{PinyinKey(4320)  /* t */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* f */{PinyinKey(1920)  /* k */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* g */{PinyinKey(3600)  /* q */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* h */{PinyinKey(4080) /* sh */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* i */{PinyinKey(156)   /* u */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* j */{PinyinKey(480)   /* c */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* k */{PinyinKey(216)   /* v */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* l */{PinyinKey(42)   /* ea */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* m */{PinyinKey(3840)  /* s */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* n */{PinyinKey(3120)  /* r */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* o */{PinyinKey(36)    /* e */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* p */{PinyinKey(30)   /* ao */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* q */{PinyinKey(2)     /* 2 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* r */{PinyinKey(1680)  /* g */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* s */{PinyinKey(2400)  /* m */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* t */{PinyinKey(2160)  /* j */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* u */{PinyinKey(5280)  /* z */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* v */{PinyinKey(1440)  /* h */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* w */{PinyinKey(3360)  /* p */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* x */{PinyinKey(1200)  /* f */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* y */{PinyinKey(720)  /* ch */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* z */{PinyinKey(4)     /* 4 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* { */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* | */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
};

static const PinyinKey __zhuyin_et_map [][3] = 
{
/*   */{PinyinKey(1)     /* 1 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ! */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* " */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* # */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* $ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* % */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* & */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ' */{PinyinKey(480)   /* c */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ( */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ) */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* * */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* + */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* , */{PinyinKey(5520) /* zh */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* - */{PinyinKey(60)  /* eng */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* . */{PinyinKey(720)  /* ch */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* / */{PinyinKey(4080) /* sh */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 0 */{PinyinKey(24)  /* ang */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 1 */{PinyinKey(5)     /* 5 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 2 */{PinyinKey(2)     /* 2 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 3 */{PinyinKey(3)     /* 3 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 4 */{PinyinKey(4)     /* 4 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 5 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 6 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 7 */{PinyinKey(3600)  /* q */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 8 */{PinyinKey(18)   /* an */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 9 */{PinyinKey(54)   /* en */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* : */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ; */{PinyinKey(5280)  /* z */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* < */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* = */{PinyinKey(66)   /* er */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* > */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ? */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* @ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* A */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* B */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* C */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* D */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* E */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* F */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* G */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* H */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* I */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* J */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* K */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* L */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* M */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* N */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* O */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* P */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Q */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* R */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* S */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* T */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* U */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* V */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* W */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* X */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Y */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Z */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* [ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* \ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ] */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ^ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* _ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ` */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* a */{PinyinKey(6)     /* a */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* b */{PinyinKey(240)   /* b */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* c */{PinyinKey(4800)  /* x */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* d */{PinyinKey(960)   /* d */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* e */{PinyinKey(72)    /* i */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* f */{PinyinKey(1200)  /* f */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* g */{PinyinKey(2160)  /* j */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* h */{PinyinKey(1440)  /* h */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* i */{PinyinKey(12)   /* ai */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* j */{PinyinKey(3120)  /* r */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* k */{PinyinKey(1920)  /* k */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* l */{PinyinKey(2880)  /* l */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* m */{PinyinKey(2400)  /* m */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* n */{PinyinKey(2640)  /* n */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* o */{PinyinKey(138)   /* o */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* p */{PinyinKey(3360)  /* p */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* q */{PinyinKey(48)   /* ei */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* r */{PinyinKey(36)    /* e */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* s */{PinyinKey(3840)  /* s */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* t */{PinyinKey(4320)  /* t */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* u */{PinyinKey(216)   /* v */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* v */{PinyinKey(1680)  /* g */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* w */{PinyinKey(42)   /* ea */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* x */{PinyinKey(156)   /* u */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* y */{PinyinKey(150)  /* ou */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* z */{PinyinKey(30)   /* ao */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* { */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* | */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
};

static const PinyinKey __zhuyin_et26_map [][3] = 
{
/*   */{PinyinKey(1)     /* 1 */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ! */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* " */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* # */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* $ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* % */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* & */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ' */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ( */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ) */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* * */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* + */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* , */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* - */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* . */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* / */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 0 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 1 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 2 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 3 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 4 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 5 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 6 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 7 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 8 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* 9 */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* : */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ; */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* < */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* = */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* > */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ? */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* @ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* A */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* B */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* C */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* D */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* E */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* F */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* G */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* H */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* I */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* J */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* K */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* L */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* M */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* N */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* O */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* P */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Q */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* R */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* S */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* T */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* U */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* V */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* W */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* X */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Y */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* Z */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* [ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* \ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ] */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ^ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* _ */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* ` */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* a */{PinyinKey(6)     /* a */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* b */{PinyinKey(240)   /* b */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* c */{PinyinKey(4800)  /* x */, PinyinKey(4080) /* sh */, PinyinKey(0)      /*  */},
/* d */{PinyinKey(960)   /* d */, PinyinKey(5)     /* 5 */, PinyinKey(0)      /*  */},
/* e */{PinyinKey(72)    /* i */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* f */{PinyinKey(1200)  /* f */, PinyinKey(2)     /* 2 */, PinyinKey(0)      /*  */},
/* g */{PinyinKey(2160)  /* j */, PinyinKey(5520) /* zh */, PinyinKey(0)      /*  */},
/* h */{PinyinKey(1440)  /* h */, PinyinKey(66)   /* er */, PinyinKey(0)      /*  */},
/* i */{PinyinKey(12)   /* ai */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* j */{PinyinKey(3120)  /* r */, PinyinKey(3)     /* 3 */, PinyinKey(0)      /*  */},
/* k */{PinyinKey(1920)  /* k */, PinyinKey(4)     /* 4 */, PinyinKey(0)      /*  */},
/* l */{PinyinKey(2880)  /* l */, PinyinKey(60)  /* eng */, PinyinKey(0)      /*  */},
/* m */{PinyinKey(2400)  /* m */, PinyinKey(18)   /* an */, PinyinKey(0)      /*  */},
/* n */{PinyinKey(2640)  /* n */, PinyinKey(54)   /* en */, PinyinKey(0)      /*  */},
/* o */{PinyinKey(138)   /* o */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* p */{PinyinKey(3360)  /* p */, PinyinKey(150)  /* ou */, PinyinKey(0)      /*  */},
/* q */{PinyinKey(5280)  /* z */, PinyinKey(48)   /* ei */, PinyinKey(0)      /*  */},
/* r */{PinyinKey(36)    /* e */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* s */{PinyinKey(3840)  /* s */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* t */{PinyinKey(4320)  /* t */, PinyinKey(24)  /* ang */, PinyinKey(0)      /*  */},
/* u */{PinyinKey(216)   /* v */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* v */{PinyinKey(1680)  /* g */, PinyinKey(3600)  /* q */, PinyinKey(0)      /*  */},
/* w */{PinyinKey(480)   /* c */, PinyinKey(42)   /* ea */, PinyinKey(0)      /*  */},
/* x */{PinyinKey(156)   /* u */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* y */{PinyinKey(720)  /* ch */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* z */{PinyinKey(30)   /* ao */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* { */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
/* | */{PinyinKey(0)      /*  */, PinyinKey(0)      /*  */, PinyinKey(0)      /*  */},
};

